"""Accounting-concept-aware matching for quarterly SEC gap fills.

Hierarchy: canonical XBRL → aliases → statement context → period type →
parent/subtotal → SEC label → semantic fallback. Ambiguous → REVIEW_REQUIRED.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from models.quarterly_presentation import QuarterlyStatementKind, SecLineItem


def _norm(text: Any) -> str:
    return " ".join(str(text or "").lower().replace("&", " and ").split())


# Concept id → aliases (workbook + SEC presentation language)
CONCEPT_ALIASES: dict[str, tuple[str, ...]] = {
    "revenue": (
        "revenue",
        "net sales",
        "sales",
        "total net revenues",
        "net revenue",
        "total revenue",
        "revenues",
    ),
    "gross_profit": ("gross profit", "gross margin dollars"),
    "operating_income": (
        "operating income",
        "income from operations",
        "operating income (loss)",
        "operating profit",
    ),
    "net_income": ("net income", "net earnings", "net income, gaap", "profit for the period"),
    "cash": (
        "cash and cash equivalents",
        "cash & cash equivalents",
        "cash, cash equivalents",
        "cash",
    ),
    "short_term_investments": (
        "short-term investments",
        "marketable securities (current)",
        "marketable securities current",
        "available for sale securities current",
    ),
    "receivables": (
        "accounts receivable",
        "trade receivables",
        "receivables, net",
        "accounts & notes receiv",
        "accounts receivable, net",
    ),
    "inventory": ("inventories", "inventory", "inventory net"),
    "current_assets": ("total current assets", "current assets"),
    "ppe": (
        "property, plant and equipment",
        "property plant and equipment",
        "pp&e",
        "property and equipment",
        "property, plant & equip",
    ),
    "goodwill": ("goodwill",),
    "intangibles": ("intangible assets", "other intangible assets", "total intangible assets"),
    "total_assets": ("total assets", "assets"),
    "accounts_payable": ("accounts payable", "trade payables", "accounts payable current"),
    "current_liabilities": ("total current liabilities", "current liabilities"),
    "st_debt": ("short-term debt", "st debt", "short term borrowings", "commercial paper"),
    "lt_debt": ("long-term debt", "lt debt", "long term debt noncurrent"),
    "total_liabilities": ("total liabilities", "liabilities"),
    "equity": (
        "total equity",
        "total shareholders' equity",
        "stockholders equity",
        "shareholders equity",
    ),
    "cfo": (
        "cash from operating",
        "cash generated by operating",
        "net cash provided by operating",
        "operating activities",
    ),
    "cfi": ("cash from investing", "cash used in investing", "investing activities"),
    "cff": ("cash from financing", "cash used in financing", "financing activities"),
    "capex": (
        "payments for acquisition of property",
        "acq of fixed",
        "capital expenditures",
        "capex",
    ),
}

# Concept → preferred XBRL tags (order = preference)
CONCEPT_XBRL: dict[str, tuple[str, ...]] = {
    "revenue": (
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "SalesRevenueNet",
        "Revenues",
    ),
    "gross_profit": ("GrossProfit",),
    "operating_income": ("OperatingIncomeLoss",),
    "net_income": ("NetIncomeLoss",),
    "cash": ("CashAndCashEquivalentsAtCarryingValue",),
    "short_term_investments": (
        "MarketableSecuritiesCurrent",
        "AvailableForSaleSecuritiesCurrent",
        "ShortTermInvestments",
    ),
    "receivables": ("AccountsReceivableNetCurrent",),
    "inventory": ("InventoryNet",),
    "current_assets": ("AssetsCurrent",),
    "ppe": ("PropertyPlantAndEquipmentNet",),
    "goodwill": ("Goodwill",),
    "intangibles": ("IntangibleAssetsNetExcludingGoodwill",),
    "total_assets": ("Assets",),
    "accounts_payable": ("AccountsPayableCurrent",),
    "current_liabilities": ("LiabilitiesCurrent",),
    "st_debt": ("ShortTermBorrowings", "CommercialPaper", "LongTermDebtCurrent"),
    "lt_debt": ("LongTermDebtNoncurrent", "LongTermDebt"),
    "total_liabilities": ("Liabilities",),
    "equity": (
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ),
    "cfo": (
        "NetCashProvidedByUsedInOperatingActivities",
        "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations",
    ),
    "cfi": ("NetCashProvidedByUsedInInvestingActivities",),
    "cff": ("NetCashProvidedByUsedInFinancingActivities",),
    "capex": ("PaymentsToAcquirePropertyPlantAndEquipment",),
}

STATEMENT_CONCEPTS: dict[QuarterlyStatementKind, frozenset[str]] = {
    QuarterlyStatementKind.INCOME: frozenset(
        {"revenue", "gross_profit", "operating_income", "net_income"}
    ),
    QuarterlyStatementKind.BALANCE_SHEET: frozenset(
        {
            "cash",
            "short_term_investments",
            "receivables",
            "inventory",
            "current_assets",
            "ppe",
            "goodwill",
            "intangibles",
            "total_assets",
            "accounts_payable",
            "current_liabilities",
            "st_debt",
            "lt_debt",
            "total_liabilities",
            "equity",
        }
    ),
    QuarterlyStatementKind.CASH_FLOW: frozenset({"cfo", "cfi", "cff", "capex"}),
}

PERIOD_FOR_STATEMENT: dict[QuarterlyStatementKind, str] = {
    QuarterlyStatementKind.INCOME: "standalone_quarter",
    QuarterlyStatementKind.BALANCE_SHEET: "instant",
    QuarterlyStatementKind.CASH_FLOW: "ytd",
}


@dataclass
class ConceptMatchResult:
    decision: str  # MATCHED | REVIEW_REQUIRED | SOURCE_MISSING | BLOCKED
    workbook_label: str
    accounting_concept: str | None = None
    sec_xbrl_concept: str | None = None
    sec_presentation_label: str | None = None
    statement: str | None = None
    period_kind: str | None = None
    match_method: str | None = None
    confidence: float = 0.0
    value: float | None = None
    alternatives: list[dict[str, Any]] = field(default_factory=list)
    reason: str = ""


def interpret_workbook_label(
    label: str,
    kind: QuarterlyStatementKind,
) -> list[str]:
    """Return ranked concept ids that could match a workbook label."""
    n = _norm(label)
    allowed = STATEMENT_CONCEPTS[kind]
    hits: list[tuple[int, str]] = []
    for concept, aliases in CONCEPT_ALIASES.items():
        if concept not in allowed:
            continue
        for alias in aliases:
            if alias in n or n in alias:
                # Prefer longer alias matches
                hits.append((len(alias), concept))
                break
    hits.sort(key=lambda t: -t[0])
    # Deduplicate preserving order
    seen: list[str] = []
    for _, c in hits:
        if c not in seen:
            seen.append(c)
    return seen


def match_sec_item_to_concept(
    concept: str,
    sec_items: list[SecLineItem],
    *,
    kind: QuarterlyStatementKind,
) -> ConceptMatchResult:
    """Match one accounting concept to SEC line items with provenance."""
    want_period = PERIOD_FOR_STATEMENT[kind]
    xbrl_prefs = CONCEPT_XBRL.get(concept, ())
    aliases = CONCEPT_ALIASES.get(concept, ())

    by_xbrl: list[SecLineItem] = []
    by_alias: list[SecLineItem] = []
    for item in sec_items:
        if item.duration_kind and item.duration_kind != want_period and kind != QuarterlyStatementKind.BALANCE_SHEET:
            # Allow instant always for BS; for IS/CF enforce duration
            if kind == QuarterlyStatementKind.INCOME and item.duration_kind != "standalone_quarter":
                if item.duration_kind != "ytd":  # ytd IS used in separate path
                    continue
            if kind == QuarterlyStatementKind.CASH_FLOW and item.duration_kind != "ytd":
                continue
        if item.xbrl_concept and item.xbrl_concept in xbrl_prefs:
            by_xbrl.append(item)
        lab = _norm(item.label)
        if any(a in lab for a in aliases):
            by_alias.append(item)

    # Prefer XBRL canonical
    if len(by_xbrl) == 1:
        hit = by_xbrl[0]
        return ConceptMatchResult(
            decision="MATCHED",
            workbook_label=concept,
            accounting_concept=concept,
            sec_xbrl_concept=hit.xbrl_concept,
            sec_presentation_label=hit.label,
            statement=kind.value,
            period_kind=hit.duration_kind,
            match_method="canonical_xbrl",
            confidence=0.95,
            value=hit.value,
            reason=f"Matched via XBRL tag {hit.xbrl_concept}",
        )
    if len(by_xbrl) > 1:
        return ConceptMatchResult(
            decision="REVIEW_REQUIRED",
            workbook_label=concept,
            accounting_concept=concept,
            statement=kind.value,
            period_kind=want_period,
            match_method="canonical_xbrl",
            confidence=0.4,
            alternatives=[
                {"label": i.label, "xbrl": i.xbrl_concept, "value": i.value} for i in by_xbrl
            ],
            reason="Multiple XBRL candidates — not guessing.",
        )

    if len(by_alias) == 1:
        hit = by_alias[0]
        return ConceptMatchResult(
            decision="MATCHED",
            workbook_label=concept,
            accounting_concept=concept,
            sec_xbrl_concept=hit.xbrl_concept,
            sec_presentation_label=hit.label,
            statement=kind.value,
            period_kind=hit.duration_kind,
            match_method="alias_synonym",
            confidence=0.85,
            value=hit.value,
            reason=f"Matched via accounting alias to SEC label '{hit.label}'",
        )
    if len(by_alias) > 1:
        return ConceptMatchResult(
            decision="REVIEW_REQUIRED",
            workbook_label=concept,
            accounting_concept=concept,
            statement=kind.value,
            period_kind=want_period,
            match_method="alias_synonym",
            confidence=0.35,
            alternatives=[
                {"label": i.label, "xbrl": i.xbrl_concept, "value": i.value} for i in by_alias
            ],
            reason="Multiple alias matches — REVIEW_REQUIRED.",
        )

    return ConceptMatchResult(
        decision="SOURCE_MISSING",
        workbook_label=concept,
        accounting_concept=concept,
        statement=kind.value,
        period_kind=want_period,
        match_method="none",
        confidence=0.0,
        reason="No SEC fact for concept; leave blank (do not invent).",
    )


def resolve_workbook_gap(
    workbook_label: str,
    kind: QuarterlyStatementKind,
    sec_items: list[SecLineItem],
) -> ConceptMatchResult:
    """Full hierarchy entry point for one blank workbook row."""
    concepts = interpret_workbook_label(workbook_label, kind)
    if not concepts:
        return ConceptMatchResult(
            decision="BLOCKED",
            workbook_label=workbook_label,
            reason="Could not interpret workbook label as a known accounting concept.",
        )
    if len(concepts) > 1:
        # Try each; if more than one MATCHED with different values → REVIEW
        matches = [match_sec_item_to_concept(c, sec_items, kind=kind) for c in concepts]
        matched = [m for m in matches if m.decision == "MATCHED"]
        if len(matched) == 1:
            m = matched[0]
            m.workbook_label = workbook_label
            return m
        if len(matched) > 1:
            vals = {m.value for m in matched}
            if len(vals) == 1:
                m = matched[0]
                m.workbook_label = workbook_label
                m.match_method = "multi_concept_consensus"
                return m
            return ConceptMatchResult(
                decision="REVIEW_REQUIRED",
                workbook_label=workbook_label,
                accounting_concept=None,
                alternatives=[
                    {
                        "concept": m.accounting_concept,
                        "label": m.sec_presentation_label,
                        "value": m.value,
                    }
                    for m in matched
                ],
                reason="Multiple plausible accounting concepts with different values.",
            )
        # none matched — return best SOURCE_MISSING
        best = matches[0]
        best.workbook_label = workbook_label
        return best

    result = match_sec_item_to_concept(concepts[0], sec_items, kind=kind)
    result.workbook_label = workbook_label
    return result
