"""Extract SEC 10-Q statement line items with duration awareness."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

from models.quarterly_presentation import QuarterlyStatementKind, SecLineItem
from services.sec_service import SecService, XbrlFact

# Ordered SEC presentation (broader line items — not Bloomberg taxonomy).
_IS_LINES: list[tuple[str, str, list[str]]] = [
    # label, duration_needed, tags
    ("Revenue", "standalone_quarter", [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "SalesRevenueNet",
        "Revenues",
    ]),
    ("Cost of sales", "standalone_quarter", [
        "CostOfGoodsAndServicesSold",
        "CostOfRevenue",
    ]),
    ("Gross profit", "standalone_quarter", ["GrossProfit"]),
    ("Research and development", "standalone_quarter", ["ResearchAndDevelopmentExpense"]),
    ("Selling, general and administrative", "standalone_quarter", [
        "SellingGeneralAndAdministrativeExpense",
    ]),
    ("Operating income", "standalone_quarter", ["OperatingIncomeLoss"]),
    ("Income before provision for income taxes", "standalone_quarter", [
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments",
    ]),
    ("Provision for income taxes", "standalone_quarter", ["IncomeTaxExpenseBenefit"]),
    ("Net income", "standalone_quarter", ["NetIncomeLoss"]),
    ("Diluted earnings per share", "standalone_quarter", ["EarningsPerShareDiluted"]),
]

_IS_YTD_LINES: list[tuple[str, str, list[str]]] = [
    (label, "ytd", tags) for label, _dur, tags in _IS_LINES
]

_BS_LINES: list[tuple[str, str, list[str]]] = [
    ("Cash and cash equivalents", "instant", ["CashAndCashEquivalentsAtCarryingValue"]),
    ("Marketable securities (current)", "instant", [
        "MarketableSecuritiesCurrent",
        "AvailableForSaleSecuritiesCurrent",
    ]),
    ("Accounts receivable, net", "instant", ["AccountsReceivableNetCurrent"]),
    ("Inventories", "instant", ["InventoryNet"]),
    ("Total current assets", "instant", ["AssetsCurrent"]),
    ("Non-current assets", "instant", ["AssetsNoncurrent"]),
    ("Total assets", "instant", ["Assets"]),
    ("Accounts payable", "instant", ["AccountsPayableCurrent"]),
    ("Total current liabilities", "instant", ["LiabilitiesCurrent"]),
    ("Total liabilities", "instant", ["Liabilities"]),
    ("Total shareholders' equity", "instant", [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ]),
    ("Short-term investments", "instant", [
        "MarketableSecuritiesCurrent",
        "ShortTermInvestments",
    ]),
    ("Property, plant and equipment", "instant", ["PropertyPlantAndEquipmentNet"]),
    ("Goodwill", "instant", ["Goodwill"]),
    ("Short-term debt", "instant", [
        "ShortTermBorrowings",
        "CommercialPaper",
        "LongTermDebtCurrent",
    ]),
    ("Long-term debt", "instant", ["LongTermDebtNoncurrent", "LongTermDebt"]),
]

_CF_LINES: list[tuple[str, str, list[str]]] = [
    # Cash flow on 10-Q is typically YTD — never label as standalone quarter.
    ("Cash generated by operating activities", "ytd", [
        "NetCashProvidedByUsedInOperatingActivities",
        "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations",
    ]),
    ("Cash used in investing activities", "ytd", [
        "NetCashProvidedByUsedInInvestingActivities",
    ]),
    ("Cash used in financing activities", "ytd", [
        "NetCashProvidedByUsedInFinancingActivities",
    ]),
    ("Payments for acquisition of property, plant and equipment", "ytd", [
        "PaymentsToAcquirePropertyPlantAndEquipment",
    ]),
    ("Repurchases of common stock", "ytd", [
        "PaymentsForRepurchaseOfCommonStock",
    ]),
    ("Payments of dividends", "ytd", [
        "PaymentsOfDividends",
        "PaymentsOfDividendsCommonStock",
    ]),
]


def _parse_date(raw: str | None) -> date | None:
    if not raw:
        return None
    text = str(raw)[:10]
    try:
        return datetime.strptime(text, "%Y-%m-%d").date()
    except ValueError:
        return None


def classify_duration_from_dates(
    start: str | None,
    end: str | None,
    *,
    fiscal_period: str | None = None,
) -> str:
    """Classify fact as standalone_quarter, ytd, or instant."""
    start_d = _parse_date(start)
    end_d = _parse_date(end)
    if start_d is None and end_d is not None:
        return "instant"
    if start_d is None or end_d is None:
        fp = (fiscal_period or "").upper()
        if fp.startswith("Q"):
            return "standalone_quarter"
        return "unknown"
    days = (end_d - start_d).days
    if days <= 100:
        return "standalone_quarter"
    return "ytd"


def classify_duration(fact: XbrlFact, entry: dict[str, Any] | None = None) -> str:
    entry = entry or {}
    return classify_duration_from_dates(
        entry.get("start"),
        entry.get("end"),
        fiscal_period=fact.fiscal_period,
    )


def _iter_tag_entries(company_facts: dict[str, Any], tag: str) -> list[dict[str, Any]]:
    facts = company_facts.get("facts") or {}
    for taxonomy in ("us-gaap", "dei", "ifrs-full"):
        payload = (facts.get(taxonomy) or {}).get(tag)
        if not payload:
            continue
        units = payload.get("units") or {}
        out: list[dict[str, Any]] = []
        for unit, entries in units.items():
            for entry in entries or []:
                row = dict(entry)
                row["_unit"] = unit
                row["_tag"] = tag
                out.append(row)
        return out
    return []


def _entry_to_fact(entry: dict[str, Any]) -> XbrlFact:
    return XbrlFact(
        tag=str(entry.get("_tag") or ""),
        taxonomy="us-gaap",
        label=str(entry.get("_tag") or ""),
        unit=str(entry.get("_unit") or "USD"),
        value=float(entry["val"]),
        fiscal_year=entry.get("fy"),
        fiscal_period=entry.get("fp"),
        form=str(entry.get("form") or ""),
        filed=str(entry.get("filed") or ""),
        accession_number=entry.get("accn"),
        frame=entry.get("frame"),
    )


def _pick_entry(
    entries: list[dict[str, Any]],
    *,
    want_duration: str,
    prefer_form: str = "10-Q",
) -> dict[str, Any] | None:
    scored: list[tuple[int, dict[str, Any]]] = []
    for entry in entries:
        if entry.get("val") is None:
            continue
        form = str(entry.get("form") or "")
        fact = _entry_to_fact(entry)
        duration = classify_duration(fact, entry)
        if want_duration == "instant":
            if entry.get("start"):
                continue
        elif duration != want_duration:
            continue
        score = 0
        if form == prefer_form:
            score += 50
        elif form == "10-K" and want_duration != "standalone_quarter":
            score += 10
        fp = str(entry.get("fp") or "")
        if fp.startswith("Q"):
            score += 20
        filed = str(entry.get("filed") or "")
        score += min(len(filed), 10)
        scored.append((score, entry))
    if not scored:
        return None
    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[0][1]


def select_latest_10q_period(company_facts: dict[str, Any]) -> tuple[int | None, str | None]:
    """Return (fy, fp) for the most recently filed 10-Q in companyfacts."""
    best: tuple[str, int, str] | None = None  # filed, fy, fp
    for tag in ("Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax", "Assets"):
        for entry in _iter_tag_entries(company_facts, tag):
            if entry.get("form") != "10-Q":
                continue
            fy = entry.get("fy")
            fp = entry.get("fp")
            filed = str(entry.get("filed") or "")
            if not isinstance(fy, int) or not fp:
                continue
            cand = (filed, fy, str(fp))
            if best is None or cand[0] > best[0]:
                best = cand
    if best is None:
        return None, None
    return best[1], best[2]


def extract_sec_10q_statement(
    company_facts: dict[str, Any],
    kind: QuarterlyStatementKind,
    *,
    fiscal_year: int | None = None,
    fiscal_period: str | None = None,
    duration_kind: str | None = None,
) -> list[SecLineItem]:
    """
    Build SEC-presented line items for one quarterly statement.

    Income: standalone_quarter (3-month) only — never YTD into quarter column.
    Cash flow: YTD only — flagged duration_kind=ytd.
    Balance sheet: instant at quarter-end.
    """
    if fiscal_year is None or fiscal_period is None:
        fiscal_year, fiscal_period = select_latest_10q_period(company_facts)

    lines_spec = {
        QuarterlyStatementKind.INCOME: _IS_YTD_LINES if duration_kind == "ytd" else _IS_LINES,
        QuarterlyStatementKind.BALANCE_SHEET: _BS_LINES,
        QuarterlyStatementKind.CASH_FLOW: _CF_LINES,
    }[kind]

    items: list[SecLineItem] = []
    for label, want_duration, tags in lines_spec:
        chosen = None
        used_tag = None
        for tag in tags:
            entries = _iter_tag_entries(company_facts, tag)
            # Prefer matching fy/fp when known
            filtered = entries
            if fiscal_year is not None:
                filtered = [e for e in entries if e.get("fy") == fiscal_year]
            if fiscal_period is not None:
                filtered = [e for e in filtered if e.get("fp") == fiscal_period] or filtered
            pick = _pick_entry(filtered, want_duration=want_duration)
            if pick is None and filtered is not entries:
                pick = _pick_entry(entries, want_duration=want_duration)
            if pick is not None:
                chosen = pick
                used_tag = tag
                break
        if chosen is None or used_tag is None:
            continue
        scale = 1.0
        unit = str(chosen.get("_unit") or "USD")
        value = float(chosen["val"])
        # Template quarterly sheets are in millions for statement totals.
        if unit.upper() == "USD" and abs(value) >= 1_000_000:
            value = value / 1_000_000.0
            unit = "USD_millions"
        items.append(
            SecLineItem(
                statement=kind.value,
                label=label,
                xbrl_concept=used_tag,
                value=value,
                period_start=chosen.get("start"),
                period_end=chosen.get("end"),
                fiscal_period=str(chosen.get("fp") or fiscal_period or ""),
                form=str(chosen.get("form") or ""),
                filing_date=str(chosen.get("filed") or ""),
                accession_number=chosen.get("accn"),
                duration_kind=want_duration,
                unit=unit,
            )
        )
    return items
