"""Extract SEC 10-Q statement line items with duration awareness.

SEC EDGAR (companyfacts) is authoritative for reported financial statements.
Cash-flow and income-statement standalone quarters may be derived from
comparable year-to-date amounts. Balance-sheet amounts are never manufactured
by subtracting consecutive statements — they are point-in-time.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

from models.quarterly_presentation import QuarterlyStatementKind, SecLineItem
from services.sec_service import XbrlFact

# Ordered SEC presentation (broader line items — not Bloomberg taxonomy).
_IS_LINES: list[tuple[str, str, list[str]]] = [
    ("Revenue", "standalone_quarter", [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "SalesRevenueNet",
        "Revenues",
    ]),
    ("Cost of sales", "standalone_quarter", [
        "CostOfGoodsAndServicesSold",
        "CostOfRevenue",
    ]),
    ("Gross profit", "standalone_quarter", ["GrossProfit"]),
    ("Research and development", "standalone_quarter", ["ResearchAndDevelopmentExpense"]),
    ("Selling, general and administrative", "standalone_quarter", [
        "SellingGeneralAndAdministrativeExpense",
    ]),
    ("Operating income", "standalone_quarter", ["OperatingIncomeLoss"]),
    ("Income before provision for income taxes", "standalone_quarter", [
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
        "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments",
    ]),
    ("Provision for income taxes", "standalone_quarter", ["IncomeTaxExpenseBenefit"]),
    ("Net income", "standalone_quarter", ["NetIncomeLoss"]),
    ("Diluted earnings per share", "standalone_quarter", ["EarningsPerShareDiluted"]),
]

_IS_YTD_LINES: list[tuple[str, str, list[str]]] = [
    (label, "ytd", tags) for label, _dur, tags in _IS_LINES
]

_BS_LINES: list[tuple[str, str, list[str]]] = [
    ("Cash and cash equivalents", "instant", ["CashAndCashEquivalentsAtCarryingValue"]),
    ("Marketable securities (current)", "instant", [
        "MarketableSecuritiesCurrent",
        "AvailableForSaleSecuritiesCurrent",
    ]),
    ("Accounts receivable, net", "instant", ["AccountsReceivableNetCurrent"]),
    ("Inventories", "instant", ["InventoryNet"]),
    ("Total current assets", "instant", ["AssetsCurrent"]),
    ("Non-current assets", "instant", ["AssetsNoncurrent"]),
    ("Total assets", "instant", ["Assets"]),
    ("Accounts payable", "instant", ["AccountsPayableCurrent"]),
    ("Total current liabilities", "instant", ["LiabilitiesCurrent"]),
    ("Total liabilities", "instant", ["Liabilities"]),
    ("Total shareholders' equity", "instant", [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ]),
    ("Short-term investments", "instant", [
        "MarketableSecuritiesCurrent",
        "ShortTermInvestments",
    ]),
    ("Property, plant and equipment", "instant", ["PropertyPlantAndEquipmentNet"]),
    ("Goodwill", "instant", ["Goodwill"]),
    ("Short-term debt", "instant", [
        "ShortTermBorrowings",
        "CommercialPaper",
        "LongTermDebtCurrent",
    ]),
    ("Long-term debt", "instant", ["LongTermDebtNoncurrent", "LongTermDebt"]),
]

_CF_LINES: list[tuple[str, str, list[str]]] = [
    ("Cash generated by operating activities", "ytd", [
        "NetCashProvidedByUsedInOperatingActivities",
        "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations",
    ]),
    ("Cash used in investing activities", "ytd", [
        "NetCashProvidedByUsedInInvestingActivities",
    ]),
    ("Cash used in financing activities", "ytd", [
        "NetCashProvidedByUsedInFinancingActivities",
    ]),
    ("Payments for acquisition of property, plant and equipment", "ytd", [
        "PaymentsToAcquirePropertyPlantAndEquipment",
    ]),
    ("Repurchases of common stock", "ytd", [
        "PaymentsForRepurchaseOfCommonStock",
    ]),
    ("Payments of dividends", "ytd", [
        "PaymentsOfDividends",
        "PaymentsOfDividendsCommonStock",
    ]),
]

_EPS_TAGS = {"EarningsPerShareDiluted", "EarningsPerShareBasic"}


def _parse_date(raw: str | None) -> date | None:
    if not raw:
        return None
    text = str(raw)[:10]
    try:
        return datetime.strptime(text, "%Y-%m-%d").date()
    except ValueError:
        return None


def classify_duration_from_dates(
    start: str | None,
    end: str | None,
    *,
    fiscal_period: str | None = None,
) -> str:
    """Classify fact as standalone_quarter, ytd, or instant."""
    start_d = _parse_date(start)
    end_d = _parse_date(end)
    if start_d is None and end_d is not None:
        return "instant"
    if start_d is None or end_d is None:
        fp = (fiscal_period or "").upper()
        if fp.startswith("Q"):
            return "standalone_quarter"
        return "unknown"
    days = (end_d - start_d).days
    if days <= 100:
        return "standalone_quarter"
    return "ytd"


def classify_duration(fact: XbrlFact, entry: dict[str, Any] | None = None) -> str:
    entry = entry or {}
    return classify_duration_from_dates(
        entry.get("start"),
        entry.get("end"),
        fiscal_period=fact.fiscal_period,
    )


def duration_bucket(start: str | None, end: str | None) -> str | None:
    """Map a duration to Q1/3m, Q2/6m, Q3/9m, or FY."""
    start_d = _parse_date(start)
    end_d = _parse_date(end)
    if start_d is None or end_d is None:
        return None
    days = (end_d - start_d).days
    if days <= 100:
        return "3m"
    if 150 <= days <= 220:
        return "6m"
    if 240 <= days <= 310:
        return "9m"
    if days >= 330:
        return "fy"
    return None


def _iter_tag_entries(company_facts: dict[str, Any], tag: str) -> list[dict[str, Any]]:
    facts = company_facts.get("facts") or {}
    for taxonomy in ("us-gaap", "dei", "ifrs-full"):
        payload = (facts.get(taxonomy) or {}).get(tag)
        if not payload:
            continue
        units = payload.get("units") or {}
        out: list[dict[str, Any]] = []
        for unit, entries in units.items():
            for entry in entries or []:
                row = dict(entry)
                row["_unit"] = unit
                row["_tag"] = tag
                out.append(row)
        return out
    return []


def _entry_to_fact(entry: dict[str, Any]) -> XbrlFact:
    return XbrlFact(
        tag=str(entry.get("_tag") or ""),
        taxonomy="us-gaap",
        label=str(entry.get("_tag") or ""),
        unit=str(entry.get("_unit") or "USD"),
        value=float(entry["val"]),
        fiscal_year=entry.get("fy"),
        fiscal_period=entry.get("fp"),
        form=str(entry.get("form") or ""),
        filed=str(entry.get("filed") or ""),
        accession_number=entry.get("accn"),
        frame=entry.get("frame"),
    )


def _is_segment(entry: dict[str, Any]) -> bool:
    frame = str(entry.get("frame") or "")
    return "segment" in frame.lower()


def _source_url(accn: str | None) -> str | None:
    if not accn:
        return None
    return (
        "https://www.sec.gov/cgi-bin/browse-edgar"
        f"?accession_number={accn}&action=getcurrent"
    )


def _scale_value(raw: float, unit: str, *, tag: str) -> tuple[float, str]:
    if tag in _EPS_TAGS:
        return float(raw), unit or "USD/shares"
    if unit.upper() == "USD" and abs(raw) >= 1_000_000:
        return float(raw) / 1_000_000.0, "USD_millions"
    return float(raw), unit or "USD"


def _entry_score(
    entry: dict[str, Any],
    *,
    want_duration: str | None,
    prefer_form: str,
    fiscal_year: int | None,
    fiscal_period: str | None,
    want_bucket: str | None = None,
) -> int | None:
    if entry.get("val") is None:
        return None
    fact = _entry_to_fact(entry)
    duration = classify_duration(fact, entry)
    bucket = duration_bucket(entry.get("start"), entry.get("end"))
    form = str(entry.get("form") or "")
    fp = str(entry.get("fp") or "").upper()
    want_fp = (fiscal_period or "").upper()

    if want_duration == "instant":
        if entry.get("start"):
            return None
    elif want_duration == "standalone_quarter":
        if duration != "standalone_quarter" and bucket != "3m":
            return None
    elif want_duration == "ytd":
        if duration != "ytd" and bucket not in {"6m", "9m", "fy"}:
            if not (want_fp in {"Q1"} and bucket == "3m"):
                return None
    elif want_duration and duration != want_duration:
        return None

    if want_bucket and bucket != want_bucket:
        return None

    if fiscal_year is not None and entry.get("fy") not in (fiscal_year, None):
        if entry.get("fy") != fiscal_year:
            return None

    score = 0
    if form == prefer_form or form.startswith(prefer_form):
        score += 50
    elif "10-K" in form and want_duration != "standalone_quarter":
        score += 20
    elif "10-K" in form and want_fp == "Q4" and bucket == "3m":
        score += 40
    if want_fp:
        if want_fp == "Q4" and fp in {"Q4", "FY"}:
            score += 25
        elif fp == want_fp:
            score += 25
    if fp.startswith("Q"):
        score += 10
    if _is_segment(entry):
        score -= 40
    filed = str(entry.get("filed") or "")
    score += min(len(filed), 10)
    # Prefer later filed (amendments)
    try:
        score += int(filed.replace("-", "")[:8] or "0") % 100
    except ValueError:
        pass
    return score


def _pick_entry(
    entries: list[dict[str, Any]],
    *,
    want_duration: str,
    prefer_form: str = "10-Q",
    fiscal_year: int | None = None,
    fiscal_period: str | None = None,
    want_bucket: str | None = None,
) -> dict[str, Any] | None:
    scored: list[tuple[int, dict[str, Any]]] = []
    for entry in entries:
        score = _entry_score(
            entry,
            want_duration=want_duration,
            prefer_form=prefer_form,
            fiscal_year=fiscal_year,
            fiscal_period=fiscal_period,
            want_bucket=want_bucket,
        )
        if score is None:
            continue
        scored.append((score, entry))
    if not scored:
        return None
    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[0][1]


def _pick_bucket(
    entries: list[dict[str, Any]],
    *,
    fiscal_year: int,
    bucket: str,
    prefer_form: str,
    fiscal_period: str | None = None,
) -> dict[str, Any] | None:
    want_duration = "standalone_quarter" if bucket == "3m" else ("instant" if bucket == "instant" else "ytd")
    if bucket == "fy":
        want_duration = "ytd"
    filtered = [e for e in entries if e.get("fy") == fiscal_year]
    pool = filtered or entries
    return _pick_entry(
        pool,
        want_duration=want_duration,
        prefer_form=prefer_form,
        fiscal_year=fiscal_year,
        fiscal_period=fiscal_period,
        want_bucket=bucket,
    )


def select_latest_10q_period(company_facts: dict[str, Any]) -> tuple[int | None, str | None]:
    """Return (fy, fp) for the most recently filed 10-Q in companyfacts."""
    best: tuple[str, int, str] | None = None
    for tag in ("Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax", "Assets"):
        for entry in _iter_tag_entries(company_facts, tag):
            if "10-Q" not in str(entry.get("form") or ""):
                continue
            fy = entry.get("fy")
            fp = entry.get("fp")
            filed = str(entry.get("filed") or "")
            if not isinstance(fy, int) or not fp:
                continue
            cand = (filed, fy, str(fp))
            if best is None or cand[0] > best[0]:
                best = cand
    if best is None:
        return None, None
    return best[1], best[2]


def _unresolved_item(
    kind: QuarterlyStatementKind,
    label: str,
    want_duration: str,
    reason: str,
    *,
    fiscal_period: str | None = None,
) -> SecLineItem:
    return SecLineItem(
        statement=kind.value,
        label=label,
        value=None,
        fiscal_period=fiscal_period,
        duration_kind=want_duration,
        extraction_method="unresolved",
        unresolved_reason=reason,
        source="sec",
    )


def _item_from_entry(
    kind: QuarterlyStatementKind,
    label: str,
    tag: str,
    entry: dict[str, Any],
    *,
    duration_kind: str,
    extraction_method: str,
    derivation: str | None = None,
    ytd_value: float | None = None,
    ytd_entry: dict[str, Any] | None = None,
) -> SecLineItem:
    raw = float(entry["val"])
    unit = str(entry.get("_unit") or "USD")
    value, unit = _scale_value(raw, unit, tag=tag)
    ytd_scaled = ytd_value
    if ytd_entry is not None and ytd_entry.get("val") is not None:
        ytd_scaled, _ = _scale_value(
            float(ytd_entry["val"]),
            str(ytd_entry.get("_unit") or "USD"),
            tag=tag,
        )
    return SecLineItem(
        statement=kind.value,
        label=label,
        xbrl_concept=tag,
        value=value,
        period_start=entry.get("start"),
        period_end=entry.get("end"),
        fiscal_period=str(entry.get("fp") or ""),
        form=str(entry.get("form") or ""),
        filing_date=str(entry.get("filed") or ""),
        accession_number=entry.get("accn"),
        source_url=_source_url(entry.get("accn")),
        duration_kind=duration_kind,
        unit=unit,
        extraction_method=extraction_method,
        derivation=derivation,
        ytd_value=ytd_scaled,
        source="sec",
    )


def derive_standalone_from_ytd(
    current: dict[str, Any],
    preceding: dict[str, Any],
    *,
    tag: str,
) -> tuple[float, str] | None:
    """Standalone = current YTD − preceding YTD, after consistent unit scaling."""
    if current.get("val") is None or preceding.get("val") is None:
        return None
    cur, cur_unit = _scale_value(float(current["val"]), str(current.get("_unit") or "USD"), tag=tag)
    prev, prev_unit = _scale_value(float(preceding["val"]), str(preceding.get("_unit") or "USD"), tag=tag)
    if cur_unit != prev_unit:
        return None
    return cur - prev, (
        f"standalone = {current.get('fp') or 'current'} YTD {cur:g} "
        f"- {preceding.get('fp') or 'preceding'} YTD {prev:g}"
    )


def _derivation_pair(
    fp: str | None,
) -> tuple[str, str, str] | None:
    """Return (current_bucket, preceding_bucket, rule) for standalone derivation."""
    q = (fp or "").upper()
    if q == "Q2":
        return "6m", "3m", "Q2 standalone = six-month YTD - Q1 YTD"
    if q == "Q3":
        return "9m", "6m", "Q3 standalone = nine-month YTD - six-month YTD"
    if q in {"Q4", "FY"}:
        return "fy", "9m", "Q4 standalone = full-year 10-K - nine-month YTD"
    return None


def _resolve_flow_or_income_line(
    company_facts: dict[str, Any],
    kind: QuarterlyStatementKind,
    label: str,
    tags: list[str],
    *,
    fiscal_year: int | None,
    fiscal_period: str | None,
    prefer_standalone: bool,
    ytd_only: bool,
) -> SecLineItem:
    want_duration = "ytd" if (ytd_only or kind == QuarterlyStatementKind.CASH_FLOW) else "standalone_quarter"
    chosen = None
    used_tag = None
    ytd_entry = None
    for tag in tags:
        entries = _iter_tag_entries(company_facts, tag)
        if not entries:
            continue
        if ytd_only:
            pick = _pick_entry(
                entries,
                want_duration="ytd",
                prefer_form="10-Q",
                fiscal_year=fiscal_year,
                fiscal_period=fiscal_period,
            )
            if pick is None and fiscal_period == "Q1":
                pick = _pick_entry(
                    entries,
                    want_duration="standalone_quarter",
                    prefer_form="10-Q",
                    fiscal_year=fiscal_year,
                    fiscal_period=fiscal_period,
                    want_bucket="3m",
                )
            if pick is not None:
                chosen, used_tag = pick, tag
                break
            continue

        if prefer_standalone:
            pick = _pick_entry(
                entries,
                want_duration="standalone_quarter",
                prefer_form="10-Q",
                fiscal_year=fiscal_year,
                fiscal_period=fiscal_period,
                want_bucket="3m",
            )
            if pick is None and (fiscal_period or "").upper() == "Q4":
                pick = _pick_entry(
                    entries,
                    want_duration="standalone_quarter",
                    prefer_form="10-K",
                    fiscal_year=fiscal_year,
                    fiscal_period="Q4",
                    want_bucket="3m",
                )
            if pick is not None:
                ytd_entry = _pick_entry(
                    entries,
                    want_duration="ytd",
                    prefer_form="10-Q",
                    fiscal_year=fiscal_year,
                    fiscal_period=fiscal_period,
                )
                chosen, used_tag = pick, tag
                break

        pair = _derivation_pair(fiscal_period)
        if pair and fiscal_year is not None:
            cur_bucket, prev_bucket, rule = pair
            cur_form = "10-K" if cur_bucket == "fy" else "10-Q"
            current = _pick_bucket(
                entries,
                fiscal_year=fiscal_year,
                bucket=cur_bucket,
                prefer_form=cur_form,
                fiscal_period="FY" if cur_bucket == "fy" else fiscal_period,
            )
            preceding = _pick_bucket(
                entries,
                fiscal_year=fiscal_year,
                bucket=prev_bucket,
                prefer_form="10-Q",
                fiscal_period="Q1" if prev_bucket == "3m" else ("Q2" if prev_bucket == "6m" else "Q3"),
            )
            if current is not None and preceding is not None:
                derived = derive_standalone_from_ytd(current, preceding, tag=tag)
                if derived is not None:
                    value, note = derived
                    ytd_scaled = None
                    if current.get("val") is not None:
                        ytd_scaled, _ = _scale_value(
                            float(current["val"]),
                            str(current.get("_unit") or "USD"),
                            tag=tag,
                        )
                    return SecLineItem(
                        statement=kind.value,
                        label=label,
                        xbrl_concept=tag,
                        value=value,
                        period_start=preceding.get("end"),
                        period_end=current.get("end"),
                        fiscal_period=str(fiscal_period or current.get("fp") or ""),
                        form=str(current.get("form") or ""),
                        filing_date=str(current.get("filed") or ""),
                        accession_number=current.get("accn"),
                        source_url=_source_url(current.get("accn")),
                        duration_kind="standalone_quarter",
                        unit="USD_millions" if tag not in _EPS_TAGS else str(current.get("_unit") or "USD/shares"),
                        extraction_method="derived_ytd_subtract",
                        derivation=f"{rule}. {note}",
                        ytd_value=ytd_scaled,
                        source="sec",
                    )

        if kind == QuarterlyStatementKind.CASH_FLOW:
            pick = _pick_entry(
                entries,
                want_duration="ytd",
                prefer_form="10-Q",
                fiscal_year=fiscal_year,
                fiscal_period=fiscal_period,
            )
            if pick is not None:
                chosen, used_tag = pick, tag
                break

    if chosen is None or used_tag is None:
        reason = (
            f"No reliable SEC match for {label} "
            f"(fy={fiscal_year} fp={fiscal_period}); not represented as zero"
        )
        return _unresolved_item(kind, label, want_duration, reason, fiscal_period=fiscal_period)

    method = "reported_ytd" if classify_duration(_entry_to_fact(chosen), chosen) == "ytd" else "reported_standalone"
    duration = "ytd" if method == "reported_ytd" else "standalone_quarter"
    return _item_from_entry(
        kind,
        label,
        used_tag,
        chosen,
        duration_kind=duration,
        extraction_method=method,
        ytd_entry=ytd_entry if method != "reported_ytd" else chosen,
    )


def _resolve_instant_line(
    company_facts: dict[str, Any],
    kind: QuarterlyStatementKind,
    label: str,
    tags: list[str],
    *,
    fiscal_year: int | None,
    fiscal_period: str | None,
) -> SecLineItem:
    for tag in tags:
        entries = _iter_tag_entries(company_facts, tag)
        pick = _pick_entry(
            entries,
            want_duration="instant",
            prefer_form="10-Q",
            fiscal_year=fiscal_year,
            fiscal_period=fiscal_period,
        )
        if pick is None and (fiscal_period or "").upper() in {"Q4", "FY"}:
            pick = _pick_entry(
                entries,
                want_duration="instant",
                prefer_form="10-K",
                fiscal_year=fiscal_year,
                fiscal_period="FY",
            )
        if pick is not None:
            return _item_from_entry(
                kind,
                label,
                tag,
                pick,
                duration_kind="instant",
                extraction_method="reported_instant",
            )
    return _unresolved_item(
        kind,
        label,
        "instant",
        (
            f"No point-in-time SEC amount for {label} "
            f"(fy={fiscal_year} fp={fiscal_period}); BS figures are not derived by subtraction"
        ),
        fiscal_period=fiscal_period,
    )


def extract_sec_10q_statement(
    company_facts: dict[str, Any],
    kind: QuarterlyStatementKind,
    *,
    fiscal_year: int | None = None,
    fiscal_period: str | None = None,
    duration_kind: str | None = None,
    include_unresolved: bool = True,
) -> list[SecLineItem]:
    """
    Build SEC-presented line items for one quarterly statement.

    Income: prefer reported 3-month standalone; otherwise derive from comparable YTD.
    Cash flow: prefer derived standalone quarter from YTD subtract; retain YTD companion.
    Balance sheet: instant at quarter-end only — never subtract consecutive BS amounts.
    Missing facts are returned unresolved (value=None); never fabricated as zero.
    """
    if fiscal_year is None or fiscal_period is None:
        fiscal_year, fiscal_period = select_latest_10q_period(company_facts)

    lines_spec = {
        QuarterlyStatementKind.INCOME: _IS_YTD_LINES if duration_kind == "ytd" else _IS_LINES,
        QuarterlyStatementKind.BALANCE_SHEET: _BS_LINES,
        QuarterlyStatementKind.CASH_FLOW: _CF_LINES,
    }[kind]

    items: list[SecLineItem] = []
    ytd_only = duration_kind == "ytd"
    for label, want_duration, tags in lines_spec:
        if kind == QuarterlyStatementKind.BALANCE_SHEET:
            item = _resolve_instant_line(
                company_facts, kind, label, tags,
                fiscal_year=fiscal_year, fiscal_period=fiscal_period,
            )
        else:
            item = _resolve_flow_or_income_line(
                company_facts,
                kind,
                label,
                tags,
                fiscal_year=fiscal_year,
                fiscal_period=fiscal_period,
                prefer_standalone=want_duration == "standalone_quarter" and not ytd_only,
                ytd_only=ytd_only,
            )
        if item.value is None and not include_unresolved:
            continue
        items.append(item)
    return items
