"""Yahoo Finance structured quarterly IS/CF data for basic-template fallback."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from models.quarterly_presentation import QuarterlyStatementKind, SecLineItem

YAHOO_QUOTE_SUMMARY = (
    "https://query2.finance.yahoo.com/v10/finance/quoteSummary/{symbol}"
    "?modules=incomeStatementHistoryQuarterly,cashflowStatementHistoryQuarterly,earningsHistory"
)

# Provenance labels for YTD resolution audit trail.
DIRECT_REPORTED = "DIRECT_REPORTED"
SECONDARY_REPORTED = "SECONDARY_REPORTED"
DERIVED_QUARTER_SUM = "DERIVED_QUARTER_SUM"
SOURCE_MISSING = "SOURCE_MISSING"

# Map Yahoo/basic fields → SEC YTD line labels for secondary lookup.
_IS_FIELD_TO_SEC_LABEL = {
    "totalRevenue": "Revenue",
    "costOfRevenue": "Cost of sales",
    "totalOperatingExpenses": "Research and development",  # partial proxy
    "operatingIncome": "Operating income",
    "netIncome": "Net income",
    "basicEPS": "Diluted earnings per share",
    "dilutedEPS": "Diluted earnings per share",
}

_CF_FIELD_TO_SEC_LABEL = {
    "totalCashFromOperatingActivities": "Cash generated by operating activities",
    "totalCashflowsFromInvestingActivities": "Cash used in investing activities",
    "totalCashFromFinancingActivities": "Cash used in financing activities",
}

# Basic template row map: (row, label, yahoo_field, in_millions)
BASIC_IS_LAYOUT: list[tuple[int, str, str, bool]] = [
    (11, "Total Revenues", "totalRevenue", True),
    (12, "Cost of Revenues", "costOfRevenue", True),
    (13, "Operating Expenses", "totalOperatingExpenses", True),
    (14, "Operating Income", "operatingIncome", True),
    (15, "Net Income", "netIncome", True),
    (16, "EPS (Basic)", "basicEPS", False),
    (17, "EPS (Diluted)", "dilutedEPS", False),
]

BASIC_CF_LAYOUT: list[tuple[int, str, str, bool]] = [
    (11, "Cash from Operating Activities", "totalCashFromOperatingActivities", True),
    (12, "Cash Used for Investments", "totalCashflowsFromInvestingActivities", True),
    (13, "Cash Used for Financing", "totalCashFromFinancingActivities", True),
    (14, "Cash at Beginning of Period", "beginPeriodCashFlow", True),
    (15, "Cash at End of Period", "endPeriodCashFlow", True),
]

_CONFLICT_TOLERANCE = 0.05  # 5% — prefer SEC/company reported over derived sum


@dataclass
class YtdFieldResolution:
    value: float | None
    provenance: str = SOURCE_MISSING
    components: list[float] | None = None
    validation_source: str | None = None
    period_identity: str | None = None  # e.g. Q2_6M_YTD, Q3_9M_YTD


@dataclass
class YahooQuarterSnapshot:
    end_date: str
    fields: dict[str, float | None] = field(default_factory=dict)


@dataclass
class YahooQuarterlyBundle:
    income_quarters: list[YahooQuarterSnapshot] = field(default_factory=list)
    cashflow_quarters: list[YahooQuarterSnapshot] = field(default_factory=list)
    source: str = "market_internet:yahoo_quoteSummary"


@dataclass
class YahooPeriodValues:
    """Resolved FQ/YTD values plus per-field YTD provenance."""

    values: dict[str, float | None] = field(default_factory=dict)
    ytd_provenance: dict[str, YtdFieldResolution] = field(default_factory=dict)


def _raw_num(obj: Any) -> float | None:
    if obj is None:
        return None
    if isinstance(obj, (int, float)):
        return float(obj)
    if isinstance(obj, dict) and "raw" in obj:
        try:
            return float(obj["raw"])
        except (TypeError, ValueError):
            return None
    return None


def _to_millions(v: float | None) -> float | None:
    if v is None:
        return None
    return round(v / 1_000_000.0, 3)


def _end_date_fmt(obj: Any) -> str:
    if isinstance(obj, dict):
        if obj.get("fmt"):
            return str(obj["fmt"])
        raw = obj.get("raw")
        if isinstance(raw, (int, float)):
            return datetime.fromtimestamp(raw, tz=timezone.utc).strftime("%Y-%m-%d")
    return ""


def _period_identity(fiscal_quarter: int) -> str:
    if fiscal_quarter == 2:
        return "Q2_6M_YTD"
    if fiscal_quarter == 3:
        return "Q3_9M_YTD"
    if fiscal_quarter == 1:
        return "Q1_3M"
    return f"Q{fiscal_quarter}"


class YahooQuarterlyStatementService:
    """Fetch and normalize Yahoo quarterly financial statements."""

    def fetch(self, ticker: str) -> YahooQuarterlyBundle:
        symbol = (ticker or "").strip().upper()
        bundle = YahooQuarterlyBundle()
        if not symbol:
            return bundle
        payload = self._get_json(YAHOO_QUOTE_SUMMARY.format(symbol=symbol))
        if not payload:
            return bundle
        try:
            result = ((payload.get("quoteSummary") or {}).get("result") or [])[0]
        except (IndexError, TypeError, KeyError):
            return bundle

        is_hist = ((result.get("incomeStatementHistoryQuarterly") or {}).get("incomeStatementHistory") or [])
        for row in is_hist:
            snap = YahooQuarterSnapshot(end_date=_end_date_fmt(row.get("endDate")))
            for _, _, field_name, in_m in BASIC_IS_LAYOUT:
                v = _raw_num(row.get(field_name))
                if in_m and v is not None:
                    v = _to_millions(v)
                snap.fields[field_name] = v
            bundle.income_quarters.append(snap)

        cf_hist = ((result.get("cashflowStatementHistoryQuarterly") or {}).get("cashflowStatements") or [])
        for row in cf_hist:
            snap = YahooQuarterSnapshot(end_date=_end_date_fmt(row.get("endDate")))
            for _, _, field_name, in_m in BASIC_CF_LAYOUT:
                v = _raw_num(row.get(field_name))
                if in_m and v is not None:
                    v = _to_millions(v)
                snap.fields[field_name] = v
            bundle.cashflow_quarters.append(snap)

        return bundle

    @staticmethod
    def _get_json(url: str) -> dict[str, Any] | None:
        req = urllib.request.Request(url, headers={"User-Agent": "HAP2-ModeA/1.0"}, method="GET")
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, ValueError):
            return None

    def values_for_periods(
        self,
        bundle: YahooQuarterlyBundle,
        kind: QuarterlyStatementKind,
        *,
        fiscal_quarter: int,
        company_facts: dict[str, Any] | None = None,
        fiscal_year: int | None = None,
        fiscal_period: str | None = None,
    ) -> YahooPeriodValues:
        """Return FQ + YTD with explicit provenance hierarchy."""
        quarters = bundle.income_quarters if kind == QuarterlyStatementKind.INCOME else bundle.cashflow_quarters
        layout = BASIC_IS_LAYOUT if kind == QuarterlyStatementKind.INCOME else BASIC_CF_LAYOUT
        result = YahooPeriodValues()
        if not quarters:
            return result

        current = quarters[0]
        prior_year_idx = 4 if len(quarters) > 4 else (1 if len(quarters) > 1 else None)
        prior = quarters[prior_year_idx] if prior_year_idx is not None else None
        sec_ytd_map = self._sec_ytd_map(kind, company_facts, fiscal_year, fiscal_period)

        for _, _, field_name, _ in layout:
            result.values[f"fq_{field_name}"] = current.fields.get(field_name)
            result.values[f"py_{field_name}"] = prior.fields.get(field_name) if prior else None

            if fiscal_quarter < 2:
                continue

            ytd_res = self._resolve_ytd(
                field_name=field_name,
                kind=kind,
                fiscal_quarter=fiscal_quarter,
                quarters=quarters,
                sec_ytd=sec_ytd_map.get(field_name),
            )
            result.ytd_provenance[field_name] = ytd_res
            result.values[f"ytd_{field_name}"] = ytd_res.value

            # Prior-year YTD: SEC first, else prior-year same-period snapshot (CF cumulative)
            py_ytd_res = self._resolve_prior_ytd(
                field_name=field_name,
                kind=kind,
                fiscal_quarter=fiscal_quarter,
                prior=prior,
                sec_ytd=sec_ytd_map.get(f"py_{field_name}"),
            )
            result.values[f"py_ytd_{field_name}"] = py_ytd_res.value
            if py_ytd_res.provenance != SOURCE_MISSING:
                result.ytd_provenance[f"py_{field_name}"] = py_ytd_res

        return result

    def _resolve_ytd(
        self,
        *,
        field_name: str,
        kind: QuarterlyStatementKind,
        fiscal_quarter: int,
        quarters: list[YahooQuarterSnapshot],
        sec_ytd: float | None,
    ) -> YtdFieldResolution:
        period_id = _period_identity(fiscal_quarter)
        n_needed = fiscal_quarter  # Q2→2 quarters, Q3→3

        # Cash Flow: Yahoo quarterly CF snapshots are cumulative YTD by nature.
        if kind == QuarterlyStatementKind.CASH_FLOW:
            direct = quarters[0].fields.get(field_name)
            if direct is not None:
                if sec_ytd is not None and abs(direct - sec_ytd) / max(abs(sec_ytd), 1) > _CONFLICT_TOLERANCE:
                    return YtdFieldResolution(
                        value=sec_ytd,
                        provenance=SECONDARY_REPORTED,
                        validation_source="sec_edgar_10q",
                        period_identity=period_id,
                    )
                return YtdFieldResolution(
                    value=direct,
                    provenance=DIRECT_REPORTED,
                    validation_source="yahoo_cashflow_quarterly_cumulative",
                    period_identity=period_id,
                )
            if sec_ytd is not None:
                return YtdFieldResolution(
                    value=sec_ytd,
                    provenance=SECONDARY_REPORTED,
                    validation_source="sec_edgar_10q",
                    period_identity=period_id,
                )
            return YtdFieldResolution(value=None, provenance=SOURCE_MISSING, period_identity=period_id)

        # Income Statement: SEC reported YTD before any derivation.
        if sec_ytd is not None:
            return YtdFieldResolution(
                value=sec_ytd,
                provenance=SECONDARY_REPORTED,
                validation_source="sec_edgar_10q",
                period_identity=period_id,
            )

        # Last resort: sum standalone Yahoo quarters (explicitly marked).
        components: list[float] = []
        for i in range(min(n_needed, len(quarters))):
            v = quarters[i].fields.get(field_name)
            if v is None:
                return YtdFieldResolution(value=None, provenance=SOURCE_MISSING, period_identity=period_id)
            components.append(v)

        derived = sum(components)
        return YtdFieldResolution(
            value=derived,
            provenance=DERIVED_QUARTER_SUM,
            components=components,
            validation_source="yahoo_quarter_sum",
            period_identity=period_id,
        )

    def _resolve_prior_ytd(
        self,
        *,
        field_name: str,
        kind: QuarterlyStatementKind,
        fiscal_quarter: int,
        prior: YahooQuarterSnapshot | None,
        sec_ytd: float | None,
    ) -> YtdFieldResolution:
        period_id = _period_identity(fiscal_quarter)
        if sec_ytd is not None:
            return YtdFieldResolution(
                value=sec_ytd,
                provenance=SECONDARY_REPORTED,
                validation_source="sec_edgar_10q_prior_year",
                period_identity=f"prior_{period_id}",
            )
        if kind == QuarterlyStatementKind.CASH_FLOW and prior is not None:
            v = prior.fields.get(field_name)
            if v is not None:
                return YtdFieldResolution(
                    value=v,
                    provenance=DIRECT_REPORTED,
                    validation_source="yahoo_cashflow_prior_year_cumulative",
                    period_identity=f"prior_{period_id}",
                )
        return YtdFieldResolution(value=None, provenance=SOURCE_MISSING, period_identity=f"prior_{period_id}")

    @staticmethod
    def _sec_ytd_map(
        kind: QuarterlyStatementKind,
        company_facts: dict[str, Any] | None,
        fiscal_year: int | None,
        fiscal_period: str | None,
    ) -> dict[str, float | None]:
        if not company_facts or not fiscal_year or not fiscal_period:
            return {}
        from services.sec_10q_statement_service import extract_sec_10q_statement

        items = extract_sec_10q_statement(
            company_facts,
            kind,
            fiscal_year=fiscal_year,
            fiscal_period=fiscal_period,
            duration_kind="ytd",
        )
        label_map = _CF_FIELD_TO_SEC_LABEL if kind == QuarterlyStatementKind.CASH_FLOW else _IS_FIELD_TO_SEC_LABEL
        out: dict[str, float | None] = {}
        for field_name, sec_label in label_map.items():
            hit = next((i for i in items if i.label == sec_label and i.value is not None), None)
            if hit:
                out[field_name] = hit.value
        return out

    def to_sec_line_items(
        self,
        period_values: YahooPeriodValues | dict[str, float | None],
        kind: QuarterlyStatementKind,
        *,
        fiscal_quarter: int,
    ) -> list[SecLineItem]:
        """Convert Yahoo values to SecLineItem-shaped records for concept matcher fallback."""
        values = period_values.values if isinstance(period_values, YahooPeriodValues) else period_values
        layout = BASIC_IS_LAYOUT if kind == QuarterlyStatementKind.INCOME else BASIC_CF_LAYOUT
        items: list[SecLineItem] = []
        for _, label, field_name, _ in layout:
            fq = values.get(f"fq_{field_name}")
            if fq is not None:
                items.append(
                    SecLineItem(
                        statement=kind.value,
                        label=label,
                        xbrl_concept=field_name,
                        value=fq,
                        duration_kind="standalone_quarter",
                    )
                )
            ytd = values.get(f"ytd_{field_name}")
            if ytd is not None and fiscal_quarter >= 2:
                items.append(
                    SecLineItem(
                        statement=kind.value,
                        label=f"{label} (YTD)",
                        xbrl_concept=field_name,
                        value=ytd,
                        duration_kind="ytd",
                    )
                )
        return items

    def provenance_report(self, period_values: YahooPeriodValues) -> dict[str, dict[str, Any]]:
        """Serialize YTD provenance for artifacts."""
        out: dict[str, dict[str, Any]] = {}
        for field, res in period_values.ytd_provenance.items():
            out[field] = {
                "value": res.value,
                "provenance": res.provenance,
                "components": res.components,
                "validation_source": res.validation_source,
                "period_identity": res.period_identity,
            }
        return out
