"""HAP analysis_engine — single-purpose financial analysis modules.

Each module accepts ``CompanyFinancialModel`` (historical FinancialSeries) and
returns structured Pydantic results. Modules never access Excel workbooks or
cells directly and contain no report-writing logic.
"""

from analysis_engine.business_quality_aggregator import (
    BUSINESS_QUALITY_MODULE_NAMES,
    BusinessQualityAggregator,
    aggregate_business_quality,
)
from analysis_engine.investment_attractiveness_aggregator import (
    INVESTMENT_ATTRACTIVENESS_MODULE_NAMES,
    InvestmentAttractivenessAggregator,
    aggregate_investment_attractiveness,
)
from analysis_engine.recommendation_engine import RecommendationEngine, generate_recommendation
from analysis_engine.base import AnalysisModule
from analysis_engine.modules import (
    BalanceSheetModule,
    BusinessOutlookModule,
    CapitalAllocationModule,
    CashFlowModule,
    DEFAULT_MODULES,
    ExpectedReturnModule,
    GrowthModule,
    MarginsModule,
    ProfitabilityModule,
    RecommendationModule,
    ValuationModule,
)
from analysis_engine.metric_comparison import (
    MetricComparisonCapable,
    attach_metric_comparisons,
    build_module_metric_comparisons,
    compare_workbook_to_hap,
    extract_metric_comparisons,
)
from analysis_engine.runner import AnalysisEngine
from analysis_engine.schemas import (
    AnalysisEngineResult,
    AnalysisModuleResult,
    AnalystAdjustmentProposal,
    BusinessQualityModuleContribution,
    BusinessQualityResult,
    ComparisonRecommendedAction,
    ComparisonStatus,
    ComponentScore,
    Evidence,
    Finding,
    HAPMetric,
    InvestmentAttractivenessModuleContribution,
    InvestmentAttractivenessResult,
    MetricComparison,
    MetricResult,
    ModuleMetricComparisons,
    OpportunityItem,
    RecommendationReason,
    RecommendationResult,
    RiskItem,
)
from canonical_model import (
    BalanceSheet,
    CashFlowStatement,
    CompanyFinancialModel,
    CompanyFinancialModelBuilder,
    FinancialPoint,
    FinancialSeries,
    IncomeStatement,
    MarketData,
    PeriodAmount,
    ValuationInputs,
    build_company_financial_model,
)
from scoring_engine import (
    GROWTH_WEIGHTS,
    PROFITABILITY_WEIGHTS,
    GrowthScoreInputs,
    ProfitabilityScoreInputs,
    score_growth,
    score_profitability,
)

__all__ = [
    "AnalysisEngine",
    "AnalysisEngineResult",
    "AnalysisModule",
    "AnalysisModuleResult",
    "AnalystAdjustmentProposal",
    "BalanceSheet",
    "BalanceSheetModule",
    "BusinessQualityAggregator",
    "BusinessQualityModuleContribution",
    "BusinessQualityResult",
    "BUSINESS_QUALITY_MODULE_NAMES",
    "BusinessOutlookModule",
    "CapitalAllocationModule",
    "CashFlowModule",
    "CashFlowStatement",
    "CompanyFinancialModel",
    "CompanyFinancialModelBuilder",
    "ComparisonRecommendedAction",
    "ComparisonStatus",
    "ComponentScore",
    "DEFAULT_MODULES",
    "Evidence",
    "ExpectedReturnModule",
    "FinancialPoint",
    "FinancialSeries",
    "Finding",
    "GrowthModule",
    "HAPMetric",
    "IncomeStatement",
    "InvestmentAttractivenessAggregator",
    "InvestmentAttractivenessModuleContribution",
    "InvestmentAttractivenessResult",
    "INVESTMENT_ATTRACTIVENESS_MODULE_NAMES",
    "MarginsModule",
    "MarketData",
    "MetricComparison",
    "MetricComparisonCapable",
    "MetricResult",
    "ModuleMetricComparisons",
    "OpportunityItem",
    "RecommendationEngine",
    "RecommendationModule",
    "RecommendationReason",
    "RecommendationResult",
    "RiskItem",
    "aggregate_business_quality",
    "aggregate_investment_attractiveness",
    "generate_recommendation",
    "attach_metric_comparisons",
    "build_module_metric_comparisons",
    "compare_workbook_to_hap",
    "extract_metric_comparisons",
    "GROWTH_WEIGHTS",
    "GrowthScoreInputs",
    "PROFITABILITY_WEIGHTS",
    "PeriodAmount",
    "ProfitabilityModule",
    "ProfitabilityScoreInputs",
    "RecommendationModule",
    "RiskItem",
    "ValuationInputs",
    "ValuationModule",
    "build_company_financial_model",
    "score_growth",
    "score_profitability",
]
